# Generated by Django 5.1.6 on 2025-03-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorat', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('type_mime', models.CharField(max_length=100)),
                ('taille', models.IntegerField()),
                ('contenu', models.BinaryField()),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrevue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrevue', models.DateTimeField()),
                ('lien_entrevue', models.URLField(max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('verification_document', 'Vérification des documents'), ('acceptee', 'Acceptée')], default='en_attente', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevues_creees', to=settings.AUTH_USER_MODEL)),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevues_conduites', to=settings.AUTH_USER_MODEL)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrevues', to='gestion_tutorat.professeur')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentProfesseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat'), ('permis_etude', "Permis d'étude"), ('permis_travail', 'Permis de travail'), ('nas', "Numéro d'assurance sociale"), ('piece_identite', "Pièce d'identité")], max_length=30)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('statut_verification', models.CharField(choices=[('en_attente', 'En attente'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_tutorat.professeur')),
                ('entrevue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_tutorat.entrevue')),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_professeur', to='gestion_tutorat.fichier')),
            ],
        ),
    ]
