# Generated by Django 5.1.6 on 2025-03-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tutorat', '0003_fichier_entrevue_documentprofesseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu')], default='inactif', max_length=10),
        ),
    ]
